---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:		"home"
keywords:    
description: 
source_link: 
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"

### template colors, used site-wide via css ###
colors:
  black: '#111111'
  grey: '#838B8B'
  white: '#f8f8f8'
  blue1: '#4c516d'
  blue2: '#979aaa'
  blue3: '#838996'
  blue4: '#989898'
  blue5: '#8b8589'
